### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by macros0** [zha-ng/zha-map#15]
`Logger: homeassistant.core
First occured: 1:14:34 (4 occurences)
Last logged: 10:01:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/zha_map/__init__.py", line 137, in build
    await self.scan_device(seed)
  File "/config/custom_components/zha_map/__init__.py", line 226, in scan_device
    nei = await Neighbour.scan_device(device)
  File "/config/custom_components/zha_map/neighbour.py", line 115, in scan_device
    await r.scan()
  File "/config/custom_components/zha_map/neighbour.py", line 123, in scan
    zdo_t.ZDOCmd.Mgmt_Lqi_req, idx, tries=3, delay=1
  File "/usr/local/lib/python3.7/site-packages/zigpy/util.py", line 88, in retry
    r = await func()
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 194, in request
    result = await asyncio.wait_for(req.result, timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Соединение потеряно. Повторное подключение ...
`

`Logger: homeassistant.core
First occured: 1 марта 2020 г., 20:59:33 (13 occurences)
Last logged: 10:01:17

Error doing job: Exception in callback SerialTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/zigpy_cc/uart.py", line 140, in data_received
    self._api.data_received(frame)
  File "/usr/local/lib/python3.7/site-packages/zigpy_cc/api.py", line 180, in data_received
    obj = ZpiObject.from_unpi_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/zigpy_cc/zpi_object.py", line 76, in from_unpi_frame
    payload = cls.read_parameters(frame.data, parameters)
  File "/usr/local/lib/python3.7/site-packages/zigpy_cc/zpi_object.py", line 149, in read_parameters
    res[name] = buffalo.read_parameter(type, options)
  File "/usr/local/lib/python3.7/site-packages/zigpy_cc/buffalo.py", line 69, in read_parameter
    elif type == ParameterType.LIST_UINT32:
  File "/usr/local/lib/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: LIST_UINT32
Соединение потеряно. Повторное подключение ...
`

**Comment by macros0** [comment]
CC2538
![image](https://user-images.githubusercontent.com/20460562/75657532-7e6a9800-5c77-11ea-940f-aaac2fa4f40d.png)
![image](https://user-images.githubusercontent.com/20460562/75653290-5b87b600-5c6e-11ea-87f8-295ca0ec91fd.png)
![image](https://user-images.githubusercontent.com/20460562/75653727-35aee100-5c6f-11ea-8819-ee0597ba96ad.png)

**Comment by Adminiuga** [comment]
Based on 
```
File "/usr/local/lib/python3.7/site-packages/zigpy_cc/zpi_object.py", line 76, in from_unpi_frame
payload = cls.read_parameters(frame.data, parameters)
File "/usr/local/lib/python3.7/site-packages/zigpy_cc/zpi_object.py", line 149, in read_parameters
res[name] = buffalo.read_parameter(type, options)
File "/usr/local/lib/python3.7/site-packages/zigpy_cc/buffalo.py", line 69, in read_parameter
elif type == ParameterType.LIST_UINT32:
File "/usr/local/lib/python3.7/enum.py", line 349, in getattr
raise AttributeError(name) from None
AttributeError: LIST_UINT32
```

traceback, it looks like `zigpy_cc` is throwing an exception when decoding a received frame from the serial port. Report an issue in zigpy_cc as it looks like to being the root cause.

**Comment by Adminiuga** [comment]
Try with the latest zigpy-cc and reopen if the issue still persist an issue in zigpy-cc repo
