### ISSUE TITLE
'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by drkavnger99** [zha-ng/zha-map#29]
Just updated and restarted home assistant and now I'm getting the following error.  

Home Assistant 115.2
ZHA-MAP Version 0.3.0
'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/zha_map/__init__.py", line 66, in scan_now_handler
    await builder.preempt_build()
  File "/config/custom_components/zha_map/__init__.py", line 125, in preempt_build
    await self.build()
  File "/config/custom_components/zha_map/__init__.py", line 138, in build
    nei = await Neighbour.scan_device(device)
  File "/config/custom_components/zha_map/neighbour.py", line 73, in scan_device
    r._update_info()
  File "/config/custom_components/zha_map/neighbour.py", line 64, in _update_info
    self.device_type = self.device.node_desc.logical_type.name
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by Adminiuga** [comment]
What radio?

**Comment by Derkades** [comment]
TI CC2531

**Comment by rujudk** [comment]
I get the same error with the zzh/CC2652R radio.

**Comment by drkavnger99** [comment]
TI CC2531 As well

**Comment by Adminiuga** [comment]
can you give 0.3.1 a try?
Should be fixed in https://github.com/zha-ng/zha-map/commit/f3365ed4510d27ff2526b8cbaa156dc770a72480
Really `zigpy-cc` should have provide a valid node descriptor

**Comment by rujudk** [comment]
0.3.1 fixes the problem for me. I am using zigpy-znp btw.

**Comment by drkavnger99** [comment]
Works now with TC CC2531.  Thank you.
