### ISSUE TITLE
'EZSPCoordinator' object has no attribute 'neighbors'

### ISSUE THREAD

**Issue by MattWestb** [zha-ng/zha-map#30]
The last update with EZSP the map module is loading OK in HA but i getting this then doing one scan:

Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.140197815383088
Source: custom_components/zha_map/neighbour.py:80
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:42:03 AM (1 occurrences)
Last logged: 9:42:03 AM
````
'EZSPCoordinator' object has no attribute 'neighbors'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/zha_map/__init__.py", line 66, in scan_now_handler
    await builder.preempt_build()
  File "/config/custom_components/zha_map/__init__.py", line 125, in preempt_build
    await self.build()
  File "/config/custom_components/zha_map/__init__.py", line 138, in build
    nei = await Neighbour.scan_device(device)
  File "/config/custom_components/zha_map/neighbour.py", line 75, in scan_device
    await r.scan()
  File "/config/custom_components/zha_map/neighbour.py", line 80, in scan
    for neighbor in self.device.neighbors:
AttributeError: 'EZSPCoordinator' object has no attribute 'neighbors'
````

The "old" version (pre zigpy 0.24.0 changes (#25)) looks working OK with EZSP.
I hope i have getting the updates right then its my testsetup for "Billy" and not old dev parts is left in the system. 
(pip3 show zigpy Name: zigpy Version: 0.24.1 
pip3 show bellows Name: bellows Version: 0.20.2)
Perhaps its one bellows issue and not ZHA-MAP.

Edit: Samantha-uks zigzag is working nice looks little like one christmas tree but  nice ;-))

**Comment by Adminiuga** [comment]
Hrm, I'll retest, but it was running fine in my environment.
Make sure both zigpy and bellows and zha_map are at right version

**Comment by MattWestb** [comment]
AH was still on 0.155.0 in my test environment . Updated to 0.115.3 and all is working with the latest map.
Sorry for making trouble for you but i was thinking i have updated both environments to the laste HA.
